### PR TITLE
(maint) add support for extra vmware configuration

### PR DESCRIPTION
**Pull request by lmayorga1980**

### CODE REVIEW

**Comment by mchllweeks** [comment]
@puppetlabs-jenkins test this please

**Comment by mchllweeks** [comment]
@lmayorga1980 Could you please prepend your commit message with (maint)?

**Comment by lmayorga1980** [comment]
@mchllweeks I believe I added some tests to it...

**Comment by mchllweeks** [comment]
Jenkins test this please

**Comment by mchllweeks** [comment]
@lmayorga1980 Everything looks good.  Could you please update the commit message to pre-pend (maint).  It looks like you just changed the PR title, but not the commit message.  Once that's done I can merge this.  Thx!

**Comment by lmayorga1980** [comment]
I just did. I have plans to add more updates to vmware provisioners for the near future.

**Comment by lmayorga1980** [comment]
I have also added support for  `vmware_desktop` plugin

**Comment by mchllweeks** [comment]
Jenkins test this please.

**Comment by mchllweeks** [comment]
Jenkins retest this please.

**Comment by lmayorga1980** [comment]
@mchllweeks seems like the tests passed.

**Comment by lmayorga1980** [comment]
@mchllweeks can it be merged now?

**Pull request merged**
