### PR TITLE
Fix `BEAKER_provision=no` workflow

### PR DESCRIPTION
**Pull request by joshuaspence**
Fixes BKR-1111 and BKR-494.

### CODE REVIEW

**Comment by kevpl** [comment]
@joshuaspence the diff isn't very readable, but with some time I was able to parse what's going on here and I'm 👍 for it.

Please add a spec test to this change, so that we don't accidentally break it in the future, and then we'll be able to get this pushed through the automation for release. Thanks for the fix!

**Comment by rbclark** [comment]
Is this still in consideration? I am currently running into this issue where I am unable to make use of `BEAKER_provision=no` which really slows down development.

On a side note, I tried adding this fix with `gem 'beaker-vagrant', git: 'https://github.com/joshuaspence/beaker-vagrant', branch: 'noprovision'` in my gemfile and ended up getting 

```Failure/Error: require 'beaker-rspec'
Beaker::Host::CommandFailure:
  Host 'server7' exited with 1 running:
   sudo su -c "cp -r .ssh /root/."
  Last 10 lines of output were:
  	cp: ‘.ssh’ and ‘/root/./.ssh’ are the same file

and also

Failure/Error: require 'beaker-rspec'
TypeError:
  can't dup NilClass

**Comment by kevpl** [comment]
@joshuaspence my first thoughts would be to verify the simpler moves you made, so for instance verifying that `get_ip_from_vagrant_file` & your method `configure` will get called from the initializer from now on. You can do that with a test where you run some `expect` statements against a `Beaker::Vagrant.new` invocation.

Something to test your new configure method would be good as well. There are plenty of things to test there, whether it's that it behaves correctly on windows, or some of the ssh details like the order or verifying that the close happens at the right time (or at all). I suspect the ssh behavior is the highest risk stuff, so I'd probably go for that myself.

One thing that I am noticing looking over your changes is that it looks like you took out the old behavior that if you had `options[:provision]` set to `false`, then the [main body of `provision`](https://github.com/puppetlabs/beaker-vagrant/blob/master/lib/beaker/hypervisor/vagrant.rb#L190-L208) would not run. I see that that makes sense for the `else` body there, since you've moved the steps it takes into `initialize`. Doesn't this mean that if you have the provision option set `false` that `vagrant destroy` will be called? I would imagine that's not what you want in this case, right?

**Comment by kevpl** [comment]
@joshuaspence last comment here is still current

**Comment by kevpl** [comment]
@joshuaspence last comment here is still current. If this hasn't progressed in a week, we'll close the PR due to inactivity.

**Comment by joshuaspence** [comment]
> One thing that I am noticing looking over your changes is that it looks like you took out the old behavior that if you had options[:provision] set to false, then the main body of provision would not run. I see that that makes sense for the else body there, since you've moved the steps it takes into initialize. Doesn't this mean that if you have the provision option set false that vagrant destroy will be called? I would imagine that's not what you want in this case, right?

Yep, I think you are right. I'll fix that now.

**Comment by kevpl** [comment]
Hi @joshuaspence. Apologies on the delay on this PR from our end. Taking another look at this, I'm still confused as to how setting `options[:provision]` to `false`, the main body of the provision method will not run anymore.

I see that you moved the file check into the `configure` method, that looks good. But it still seems to me that when `provision` is called, `vagrant destroy` will still be called if the provision setting is false, unlike previous behavior. Am I reading this incorrectly?

**Comment by LTangaF** [comment]
I've got an issue at work with this branch where ssh on Windows guests doesn't get provided with the environment necessary to find **facter**. The stack trace indicates that beaker is calling `cmd.exe /c facter osfamily`.  I think `facter` is actually deprecated and it should be using some variation of `puppet facts`, but that's secondary to the fact that this patch breaks something about the needed environment for Windows guests.

It _does_ seem to solve the connection issue on `BEAKER_provision=no` beaker runs, though.

I'll try to get the stacktrace out (Github logins are presently blocked by my employer) and into this PR.

**Comment by kevpl** [comment]
my last comment is still current

**Comment by LTangaF** [comment]
@kevpl I'm not sure why it successfully skips most of provisioning. It's a little confusing looking at the code why it wouldn't run the destroy and up commands regardless of these changes. However, I can confirm that it doesn't and does resolve the second provision ssh issue.

I was able to fix the issue that I found with this branch that I posted about earlier today by sticking a call to `super` at the top of the new `configure` override method.

**Comment by LTangaF** [comment]
I think I see. That env var sets an option flag that is used in a number of places and I _think_ it is the beaker network manager that honors that gate, so it never ends up calling the hypervisor provision method.

**Comment by kevpl** [comment]
Doing an inspection of network_manager's provision method, I see what you're referring to:

- context: beaker-rspec's [spec_helper.rb#30](https://github.com/puppetlabs/beaker-rspec/blob/da9259ffab8fdb248b3fa5c2e808f94a3b71625a/lib/beaker-rspec/spec_helper.rb#L30) sets `options[:provision] => false`
- [provision](https://github.com/puppetlabs/beaker/blob/20a97ef052626c3cde83dd9f259964ea3e6e7a6d/lib/beaker/network_manager.rb#L51) calls Hypervisor.create ([network_manager.rb#73](https://github.com/puppetlabs/beaker/blob/20a97ef052626c3cde83dd9f259964ea3e6e7a6d/lib/beaker/network_manager.rb#L73))
- [Hypervisor.create](https://github.com/puppetlabs/beaker/blob/89671c82d9eb959d068c2ab14e74c0aa83b85784/lib/beaker/hypervisor.rb#L20) guards its `hypervisor.provision` call with a check against `options[:provision]` ([hypervisor.rb#37](https://github.com/puppetlabs/beaker/blob/89671c82d9eb959d068c2ab14e74c0aa83b85784/lib/beaker/hypervisor.rb#L37))

so the change means that the provision method will now rely on the safety & knowledge of its callers rather than securing itself against being called when `options[:provision]` is `false`. My opinion is that this isn't as good, but I'm fine with it if it's what beaker-vagrant users want.

Alright, let's get this thing into testing:
Jenkins, test this please.

**Comment by kevpl** [comment]
Looks like the failures are unrelated to your changes (they happen on master as well).

@joshuaspence, please pre-pend a reference to one of the fixed tickets (BKR-1111 and BKR-494) according to our [contributor guidelines](https://github.com/puppetlabs/beaker-vagrant/#contributing). Once that's done, we should be able to look to merging & releasing this change.

**Comment by joshuaspence** [comment]
@kevpl, thanks for taking a look at this and sorry I didn't get a chance to respond to your comments. I'll update the commit message now.

**Comment by kevpl** [comment]
retest this please

**Pull request merged**
