### PR TITLE
add support for ioapic for virtualbox

### PR DESCRIPTION
**Pull request by lmayorga1980**

### CODE REVIEW

**Comment by lmayorga1980** [comment]
@mchllweeks @kevpl 

Could you please this PR?

**Comment by ericwilliamson** [comment]
Jenkins, test this please

**Comment by mchllweeks** [comment]
@puppetlabs-jenkins retest this please

**Comment by ericwilliamson** [comment]
Jenkins, test this please

**Comment by ericwilliamson** [comment]
@lmayorga1980 Thanks for your PR. We are currently having some issues with our internal jenkins infra unrelated to your PR. As soon as we get that fixed we will get this merged in.

**Comment by lmayorga1980** [comment]
👍🏼

**Comment by ericwilliamson** [comment]
Jenkins, test this please

**Comment by lmayorga1980** [comment]
@ericwilliamson a tag `0.2.1` would be nice.

**Comment by ericwilliamson** [comment]
Hi @lmayorga1980  - Our CI system is performing a few more final validation checks and will automatically tag and release the new version once everything has passed. Shouldn't be long now.

**Comment by ericwilliamson** [comment]
@lmayorga1980 0.2.1 has been released 

https://rubygems.org/gems/beaker-vagrant/versions/0.2.1 
https://github.com/puppetlabs/beaker-vagrant/releases/tag/0.2.1

**Pull request merged**
